[platformio]
default_envs = esp32_sub_controller

[env]
framework = arduino
monitor_speed = 115200
build_flags = -O2 -Wall

[env:esp32_sub_controller]
platform = espressif32
board = esp32dev
build_flags = 
    ${env.build_flags}
    -D CORE_DEBUG_LEVEL=1
lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    madhephaestus/ESP32Servo @ ^3.0.5

[env:stm32_sub_controller]
platform = ststm32
board = bluepill_f103c8
upload_protocol = stlink
lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
